// AUTOGENERATED - DO NOT MODIFY
import CustomerDetails from '../src/views/CustomerDetails';

export * from '@stripe/ui-extension-sdk/version';
export const BUILD_TIME = '2025-08-13 01:22:34.331354 -0500 EST m=+1.359667668';

export { 
  CustomerDetails	
 };

export default {
  "id": "com.pepperlytics.sales-tracker",
  "version": "1.0.1",
  "name": "Pepperlytics Sales Tracker",
  "icon": "icon.png",
  "permissions": [
    {
      "permission": "charge_read",
      "purpose": "Read payment data to track and attribute sales to marketing campaigns"
    },
    {
      "permission": "checkout_session_read",
      "purpose": "Access checkout session data for sales attribution and tracking"
    },
    {
      "permission": "customer_read",
      "purpose": "Read customer information to enhance sales tracking and attribution"
    },
    {
      "permission": "payment_intent_read",
      "purpose": "Access payment intent data for comprehensive sales tracking"
    }
  ],
  "connect_permissions": null,
  "ui_extension": {
    "views": [
      {
        "viewport": "stripe.dashboard.customer.detail",
        "component": "CustomerDetails"
      }
    ],
    "content_security_policy": {
      "connect-src": null,
      "image-src": null,
      "purpose": ""
    }
  },
  "distribution_type": "private"
};
